<?php

namespace App\Http\Controllers;

use Carbon\Carbon;

class PageController extends Controller
{
    public function home()
    {
        return view('pages.home');
    }
    public function about_us()
    {
        return view('pages.about-us');
    }
    public function services()
    {
        return view('pages.services');
    }
    public function show_service($id)
    {
        $service = [
            (object) [
                'id' => 1,
                'title' => 'General Services',
                'img' => 'assets/service-img1.png',
                'desc' => 'Our General Services provide the foundation of healthcare at Prime Doctors Medical Center. This service is designed to address the everyday medical needs of individuals and families, ensuring that essential care is always within reach. From routine check-ups and preventive screenings to minor treatments and lifestyle guidance, General Services are meant to keep you healthy, informed, and protected at every stage of life.
        It is through these services that patients establish a trusted relationship with our doctors, allowing for continuous monitoring of health and early detection of potential concerns. Whether you are managing a chronic condition, seeking preventive advice, or simply needing a professional consultation, our General Services are built to offer convenient, reliable, and personalized care that adapts to your needs',
                'inclusions' => [
                    'Routine check-ups and physical exams',
                    'Preventive screenings and vaccinations',
                    'Diagnosis and treatment of common illnesses',
                    'Management of chronic conditions (e.g., diabetes, hypertension)',
                    'Health education and lifestyle counseling',
                ],
                'why_it_matters' => 'General Services play a vital role in maintaining long-term health and preventing serious illnesses. By providing accessible and comprehensive care, these services help individuals stay proactive about their health, catch potential issues early, and manage existing conditions effectively. Regular interactions with healthcare providers through General Services foster a deeper understanding of personal health, empowering patients to make informed decisions and lead healthier lives.',
                'benefits_for_patients' => [
                    'Convenient access to essential healthcare services',
                    'Early detection and prevention of health issues',
                    'Cost-effective approach to maintaining wellness',
                ]
            ],
            (object) [
                'id' => 2,
                'title' => 'Specialized Departments',
                'img' => 'assets/service-img1.png',
                'desc' => 'Our General Services provide the foundation of healthcare at Prime Doctors Medical Center. This service is designed to address the everyday medical needs of individuals and families, ensuring that essential care is always within reach. From routine check-ups and preventive screenings to minor treatments and lifestyle guidance, General Services are meant to keep you healthy, informed, and protected at every stage of life.
        It is through these services that patients establish a trusted relationship with our doctors, allowing for continuous monitoring of health and early detection of potential concerns. Whether you are managing a chronic condition, seeking preventive advice, or simply needing a professional consultation, our General Services are built to offer convenient, reliable, and personalized care that adapts to your needs',
                'inclusions' => [
                    'Routine check-ups and physical exams',
                    'Preventive screenings and vaccinations',
                    'Diagnosis and treatment of common illnesses',
                    'Management of chronic conditions (e.g., diabetes, hypertension)',
                    'Health education and lifestyle counseling',
                ],
                'why_it_matters' => 'General Services play a vital role in maintaining long-term health and preventing serious illnesses. By providing accessible and comprehensive care, these services help individuals stay proactive about their health, catch potential issues early, and manage existing conditions effectively. Regular interactions with healthcare providers through General Services foster a deeper understanding of personal health, empowering patients to make informed decisions and lead healthier lives.',
                'benefits_for_patients' => [
                    'Convenient access to essential healthcare services',
                    'Early detection and prevention of health issues',
                    'Cost-effective approach to maintaining wellness',
                ]
            ],
            (object) [
                'id' => 3,
                'title' => 'Emergency & Critical Care',
                'img' => 'assets/service-img1.png',
                'desc' => 'Our General Services provide the foundation of healthcare at Prime Doctors Medical Center. This service is designed to address the everyday medical needs of individuals and families, ensuring that essential care is always within reach. From routine check-ups and preventive screenings to minor treatments and lifestyle guidance, General Services are meant to keep you healthy, informed, and protected at every stage of life.
        It is through these services that patients establish a trusted relationship with our doctors, allowing for continuous monitoring of health and early detection of potential concerns. Whether you are managing a chronic condition, seeking preventive advice, or simply needing a professional consultation, our General Services are built to offer convenient, reliable, and personalized care that adapts to your needs',
                'inclusions' => [
                    'Routine check-ups and physical exams',
                    'Preventive screenings and vaccinations',
                    'Diagnosis and treatment of common illnesses',
                    'Management of chronic conditions (e.g., diabetes, hypertension)',
                    'Health education and lifestyle counseling',
                ],
                'why_it_matters' => 'General Services play a vital role in maintaining long-term health and preventing serious illnesses. By providing accessible and comprehensive care, these services help individuals stay proactive about their health, catch potential issues early, and manage existing conditions effectively. Regular interactions with healthcare providers through General Services foster a deeper understanding of personal health, empowering patients to make informed decisions and lead healthier lives.',
                'benefits_for_patients' => [
                    'Convenient access to essential healthcare services',
                    'Early detection and prevention of health issues',
                    'Cost-effective approach to maintaining wellness',
                ]
            ],
        ];

        $service = collect($service)->where('id', $id)->first();

        return view('pages.show_service', compact('service'));
    }

    public function careers()
    {
        $careers = [
            (object) [
                'id' => 1,
                'img' => 'assets/careers-img2.png',
                'title' => 'Medical Technologist',
                'location' => 'Makati, Metro Manila',
                'type' => 'Full-time',
                'date' => '2023-10-01',
                'vacancy' => 3,
                'description' => 'We are seeking a dedicated and compassionate Medical Doctor to join our healthcare team. The ideal candidate will be responsible for diagnosing and treating patients, providing preventive care, and promoting overall health and wellness. The Medical Doctor will work closely with other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 2,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 3,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 4,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 5,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 6,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 7,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 8,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 9,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 10,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 11,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 12,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
        ];

        foreach ($careers as $career) {
            $postedDate = Carbon::parse($career->date);
            $career->monthsAgo = $postedDate->diffInMonths(Carbon::now());
        }

        $careers_count = count($careers);

        return view('pages.careers', compact('careers', 'careers_count'));
    }

    public function show_career($id)
    {
        $career = [
            (object) [
                'id' => 1,
                'img' => 'assets/careers-img2.png',
                'title' => 'Medical Technologist',
                'location' => 'Makati, Metro Manila',
                'type' => 'Full-time',
                'experience' => '1-2 years',
                'date' => '2023-10-01',
                'vacancy' => 3,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',

                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'description' => 'We are seeking a dedicated and compassionate Medical Doctor to join our healthcare team. The ideal candidate will be responsible for diagnosing and treating patients, providing preventive care, and promoting overall health and wellness. The Medical Doctor will work closely with other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 2,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 3,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 4,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 5,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 6,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 7,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 8,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 9,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 10,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 11,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
            (object) [
                'id' => 12,
                'img' => 'assets/careers-img1.png',
                'title' => 'Registered Nurse (RN)',
                'location' => 'Makati, Metro Manila',
                'type' => 'Part-time',
                'experience' => '1-2 years',
                'date' => '2024-10-01',
                'vacancy' => 4,
                'qualifications' => [
                    'Medical degree from an accredited institution.',
                    'Valid medical license to practice in the Philippines.',
                    'Proven experience as a Medical Doctor or in a similar role.',
                    'Strong knowledge of medical procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
                'key_responsibilty' => [
                    'Conduct thorough medical examinations and assessments of patients.',
                    'Diagnose and treat a wide range of medical conditions and illnesses.',
                    'Prescribe medications and therapies as needed.',
                    'Provide preventive care, including vaccinations and health screenings.',
                    'Educate patients on health maintenance and disease prevention.',
                    'Collaborate with other healthcare professionals to develop and implement treatment plans.',
                    'Maintain accurate and up-to-date patient records.',
                    'Stay informed about the latest medical research and advancements in healthcare.',
                ],
                'overview' => 'At Prime Doctors Medical Center, our Registered Nurses play a vital role in delivering quality healthcare to patients and their families. This position requires a compassionate and detail-oriented professional who can provide direct patient care, assist physicians during examinations and procedures, and ensure that all patients receive the highest standard of medical attention in a safe and supportive environment.',
                'date_updated' => '2023-09-15',
                'description' => 'We are looking for a skilled and compassionate Registered Nurse to join our healthcare team. The ideal candidate will be responsible for providing high-quality nursing care to patients, assisting with medical procedures, and promoting overall health and wellness. The Registered Nurse will work closely with doctors and other healthcare professionals to ensure comprehensive patient care.',
                'responsibilities' => [
                    'Provide direct nursing care to patients, including administering medications and treatments.',
                    'Monitor patients\' vital signs and overall health status.',
                    'Assist doctors with medical procedures and examinations.',
                    'Educate patients and their families on health maintenance and disease prevention.',
                    'Maintain accurate and up-to-date patient records.',
                    'Collaborate with other healthcare professionals to develop and implement care plans.',
                    'Ensure a safe and clean environment for patients.',
                    'Stay informed about the latest nursing practices and advancements in healthcare.',
                ],
                'qualifications' => [
                    'Nursing degree from an accredited institution.',
                    'Valid nursing license to practice in the Philippines.',
                    'Proven experience as a Registered Nurse or in a similar role.',
                    'Strong knowledge of nursing procedures, treatments, and protocols.',
                    'Excellent communication and interpersonal skills.',
                    'Ability to work effectively in a team-oriented environment.',
                    'Compassionate and patient-focused approach to care.',
                ],
            ],
        ];

        foreach ($career as $item) {
            $postedDate = Carbon::parse($item->date);
            $item->monthsAgo = $postedDate->diffInMonths(Carbon::now());
        }

        $career = collect($career)->where('id', $id)->first();

        return view('pages.show_career', compact('career'));
    }

    public function find_a_doctor()
    {

        $doctors = [
            (object) [
                'id' => 1,
                'name' => 'Charles Cuizon',
                'gender' => 'Male',
                'language' => 'Bisaya',
                'specialization' => 'Consultant Pediatrician',
                'subSpecialization' => '',
            ],
            (object) [
                'id' => 2,
                'name' => 'Lorem Ipsum',
                'gender' => 'Female',
                'language' => 'Bisaya',
                'specialization' => 'Cardiologist',
                'subSpecialization' => '',
            ],
        ];

        return view('pages.find-a-doctor', compact('doctors'));
    }

    public function show_doctor($id)
    {
        $doctors = [
            (object) [
                'id' => 1,
                'name' => 'Dr. Charles Cuizon',
                'gender' => 'Male',
                'language' => 'Bisaya',
                'specialization' => 'Consultant Pediatrician',
                'subSpecialization' => '',
            ],
            (object) [
                'id' => 2,
                'name' => 'Dr. Lorem Ipsum',
                'gender' => 'Female',
                'language' => 'Bisaya',
                'specialization' => 'Cardiologist',
                'subSpecialization' => '',
            ],
            (object) [
                'id' => 3,
                'name' => 'Dr. Atlas Fox',
                'gender' => 'Female',
                'language' => 'Bisaya',
                'specialization' => 'Consultant Pediatrician',
                'subSpecialization' => '',
            ],
            (object) [
                'id' => 4,
                'name' => 'Dr. Jugger Naut',
                'gender' => 'Male',
                'language' => 'Bisaya',
                'specialization' => 'Cardiologist',
                'subSpecialization' => '',
            ],
        ];

        $doctor = collect($doctors)->where('id', $id)->first();
        $doctor_count = collect($doctors)->where('id', $id)->count();

        $related_doctors = collect($doctors)->where('specialization', $doctor->specialization)->all();
        $related_doctors_count = collect($doctors)->where('specialization', $doctor->specialization)->count();

        return view('pages.find-a-doctor-singlepage', compact('doctor', 'doctor_count', 'related_doctors_count', 'related_doctors'));
    }

    public function doctor_details($id)
    {
        $doctors = [
            (object) [
                'id' => 1,
                'profile_img_id' => null,
                'name' => 'Dr. Charles Cuizon',
                'gender' => 'Male',
                'language' => 'Bisaya',
                'specialization' => 'Consultant Pediatrician',
                'subSpecialization' => null,
                'clinic_room_number' => 'Room 101, West Wing',
                'phone_number' => '+63 912 345 6789',
                'language' => 'English, Filipino, Bisaya',
                'clinic_hours' => 'Monday to Friday: 9:00 AM - 5:00 PM',
                'telephone' => '+1 (555) 123-4567',
            ],
            (object) [
                'id' => 2,
                'profile_img_id' => null,
                'name' => 'Dr. Lorem Ipsum',
                'gender' => 'Female',
                'language' => 'Bisaya',
                'specialization' => 'Cardiologist',
                'subSpecialization' => null,
                'clinic_room_number' => 'Room 101, West Wing',
                'phone_number' => '+63 912 345 6789',
                'language' => 'English, Filipino, Bisaya',
                'clinic_hours' => 'Monday to Friday: 9:00 AM - 5:00 PM',
                'telephone' => '+1 (555) 123-4567',
            ],
            (object) [
                'id' => 3,
                'profile_img_id' => null,
                'name' => 'Dr. Atlas Fox',
                'gender' => 'Female',
                'language' => 'Bisaya',
                'specialization' => 'Consultant Pediatrician',
                'subSpecialization' => null,
                'clinic_room_number' => 'Room 101, West Wing',
                'phone_number' => '+63 912 345 6789',
                'language' => 'English, Filipino, Bisaya',
                'clinic_hours' => 'Monday to Friday: 9:00 AM - 5:00 PM',
                'telephone' => '+1 (555) 123-4567',
            ],
            (object) [
                'id' => 4,
                'profile_img_id' => null,
                'name' => 'Dr. Jugger Naut',
                'gender' => 'Male',
                'language' => 'Bisaya',
                'specialization' => 'Cardiologist',
                'subSpecialization' => null,
                'clinic_room_number' => 'Room 101, West Wing',
                'phone_number' => '+63 912 345 6789',
                'language' => 'English, Filipino, Bisaya',
                'clinic_hours' => 'Monday to Friday: 9:00 AM - 5:00 PM',
                'telephone' => '+1 (555) 123-4567',
            ],
        ];

        $doctor = collect($doctors)->where('id', $id)->first();

        return view('pages.doctor-details', compact('doctor'));
    }

    public function news_and_events()
    {
        $news = [
            (object) [
                'id' => 1,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img1.png',
                'title' => 'Prime Doctors Medical Center Launches New Telemedicine Services',
                'date' => '2023-09-10',
                'excerpt' => 'Prime Doctors Medical Center is excited to announce the launch of our new telemedicine services, allowing patients to consult with our healthcare professionals from the comfort of their own homes.',
            ],
            (object) [
                'id' => 2,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 3,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 4,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 5,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 6,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 7,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 8,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
            (object) [
                'id' => 9,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Health Tips for the Flu Season',
                'date' => '2023-10-05',
                'excerpt' => 'As the flu season approaches, it\'s important to take preventive measures to protect yourself and your loved ones. Here are some essential health tips to keep in mind.',
            ],
        ];


        return view('pages.news-and-events', compact('news'));
    }

    public function show_news($id)
    {
        $all_news = [
            (object) [
                'id' => 1,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img1.png',
                'title' => 'Prime Doctors Medical Center Launches New Telemedicine Services',
                'date' => '2023-09-10',
                'excerpt' => 'Prime Doctors Medical Center introduces telemedicine consultations, offering patients access to quality healthcare without leaving their homes.',
            ],
            (object) [
                'id' => 2,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img2.png',
                'title' => 'Community Blood Donation Drive Exceeds Expectations',
                'date' => '2023-09-25',
                'excerpt' => 'The recent community blood donation event successfully gathered over 150 donors, providing critical blood supply to local hospitals.',
            ],
            (object) [
                'id' => 3,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img3.png',
                'title' => 'New Diagnostic Center Opens in Cebu City',
                'date' => '2023-10-05',
                'excerpt' => 'Prime Doctors Medical Center expands its facilities with a new diagnostic center, offering advanced imaging and laboratory services.',
            ],
            (object) [
                'id' => 4,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img4.png',
                'title' => 'Wellness Seminar Promotes Healthy Living Habits',
                'date' => '2023-10-15',
                'excerpt' => 'Employees and patients joined the hospital’s wellness seminar focusing on mental health, nutrition, and exercise routines.',
            ],
            (object) [
                'id' => 5,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img5.png',
                'title' => 'Doctors Celebrate Medical Professionals Day 2023',
                'date' => '2023-10-28',
                'excerpt' => 'Prime Doctors Medical Center honors its dedicated healthcare professionals with a day of recognition and celebration.',
            ],
            (object) [
                'id' => 6,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img6.png',
                'title' => 'Hospital Implements Eco-Friendly Waste Management',
                'date' => '2023-11-03',
                'excerpt' => 'The medical center adopts a new waste segregation program to promote sustainability and reduce environmental impact.',
            ],
            (object) [
                'id' => 7,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img7.png',
                'title' => 'Free Health Check-Up for Senior Citizens Announced',
                'date' => '2023-11-18',
                'excerpt' => 'Prime Doctors Medical Center offers free annual check-ups for senior citizens as part of its community outreach initiative.',
            ],
            (object) [
                'id' => 8,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img8.png',
                'title' => 'Emergency Department Upgrades Equipment',
                'date' => '2023-11-28',
                'excerpt' => 'The hospital’s emergency department now features upgraded life-saving equipment to improve response time and patient outcomes.',
            ],
            (object) [
                'id' => 9,
                'thumbnail_image_id' => null,
                'img' => 'assets/news-img9.png',
                'title' => 'Christmas Charity Program Brings Smiles to Children',
                'date' => '2023-12-15',
                'excerpt' => 'Staff and volunteers of Prime Doctors Medical Center visited local communities to distribute gifts and host a children’s Christmas party.',
            ],
        ];



        $collection = collect($all_news);

        $news = $collection->where('id', $id)->first();


        $latest_news = $collection
            ->where('id', '!=', $id)
            ->sortByDesc('date')
            ->take(3);

        if (!$news) {
            abort(404);
        }

        return view('pages.news-and-event-singlepage', compact('news', 'latest_news'));
    }

    public function contact_us()
    {
        return view('pages.contact-us');
    }
}
